<a href="https://colab.research.google.com/github/vrajsavliya/ml_learning/blob/main/Pandas_1_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

best for manuplating the whole dataset.

*.. Pandas have two objects 1)series
2)dataframe

In [2]:
import numpy as np
import pandas as pd # is used to import pandas

## Series from lists

There are different ways to build the series

In [3]:
# using arrays or can say python list
country =['India','pak','USA','Nepal']
pd.Series(country)

0    India
1      pak
2      USA
3    Nepal
dtype: object

In [5]:
#Integer type series
runs = [13,12,3,4,5,62,4,533,5]
pd.Series(runs,dtype=np.int32)

0     13
1     12
2      3
3      4
4      5
5     62
6      4
7    533
8      5
dtype: int32

In [7]:
# Custom indexing and integer list

marks = [80,99,75,89]
subjects = ['english','math','hindi','SS']

pd.Series(marks,index=subjects) #Custom index bana ne ke liyee best hai yee

english    80
math       99
hindi      75
SS         89
dtype: int64

In [10]:
# setting a name
pd.Series(marks,index=subjects,name='Vraj svliya ke marks')

english    80
math       99
hindi      75
SS         89
Name: Vraj svliya ke marks, dtype: int64

## Series from dict

In [12]:
marks = {
    'maths' : 99,
    'English' : 89,
    'Hindi' : 79,
    'Science' : 86
}

marks_series = pd.Series(marks,name = 'Vraj Savliya ke Marks')
marks_series

maths      99
English    89
Hindi      79
Science    86
Name: Vraj Savliya ke Marks, dtype: int64

## Series Attributes

In [13]:
#size

#tell about the number of items or can say tell about the size
marks_series.size

4

In [14]:
#dtype

marks_series.dtype

dtype('int64')

In [15]:
# name

marks_series.name

'Vraj Savliya ke Marks'

In [16]:
# is_uniuqe

marks_series.is_unique

True

In [17]:
#index

marks_series.index

Index(['maths', 'English', 'Hindi', 'Science'], dtype='object')

In [20]:
# values

type(marks_series.values)
marks_series.values

array([99, 89, 79, 86])

## Series using read_csv

In [36]:
# with one col
#jub bhi hum pd.read_csv krr te hai na to pandas ausko dataframe ke format me store krr te hai aur na ki series me

subs = pd.read_csv('/content/subs.csv')
subs = subs.squeeze("columns")
type(subs)
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [39]:
# with 2 cols

kohli = pd.read_csv('/content/kohli_ipl.csv',index_col = 'match_no')
kohli = kohli.squeeze('columns')

kohli

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [40]:
movies = pd.read_csv('/content/bollywood.csv',index_col = 'movie')
movies = movies.squeeze('columns')
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object